import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Gauge, Layers3, ShieldCheck } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Beamtro — A cleaner way to connect" }, { name: "description", content: "Learn why Beamtro makes quick browser-based collaboration simpler." },
  { property: "og:title", content: "About Beamtro" }, { property: "og:description", content: "A cleaner way to connect in one temporary room." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: AboutPage });

function AboutPage() { const features = [{ icon: Gauge, title: "Fast to start", copy: "Open Beamtro, create a room, and share a short code or link in seconds." }, { icon: Layers3, title: "Everything in one place", copy: "Text chat, voice, video, and screen sharing all live in the same room." }, { icon: ShieldCheck, title: "Simple and private", copy: "No registration, no heavy setup, and a focused experience designed for quick collaboration." }]; return <div className="min-h-screen bg-background"><SiteHeader /><main className="mx-auto max-w-6xl px-5 py-16 sm:py-24"><span className="eyebrow">About Beamtro</span><h1 className="mt-5 max-w-3xl text-balance font-display text-5xl font-bold leading-none sm:text-6xl">A cleaner way to connect in a room.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Beamtro is a lightweight browser-based experience for creating quick rooms where people can talk, chat, share their screen, and jump into a call without creating an account or installing anything.</p><div className="mt-14 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, copy }) => <article className="feature-card" key={title}><span className="feature-icon"><Icon /></span><h2 className="mt-5 font-display text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{copy}</p></article>)}</div><section className="creator-band"><div><p className="font-display text-xl font-semibold">Built by Abdul Basit</p><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Beamtro was created by Abdul Basit, also known as Archer, as a practical and modern way to bring people into a shared space for conversations, support, and presentation-style sessions.</p></div><a href="https://abdulbasit-archer.vercel.app/" target="_blank" rel="noreferrer" className="footer-link bg-foreground text-background">Visit the portfolio <ArrowUpRight /></a></section></main><SiteFooter /></div>; }
