import { createFileRoute } from "@tanstack/react-router";
import { Camera, CircleHelp, Link2, MessageSquare, MonitorUp, Radio } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

export const Route = createFileRoute("/help")({ head: () => ({ meta: [
  { title: "Beamtro Help — Get connected quickly" }, { name: "description", content: "Short guides for creating, joining, and using a Beamtro room." },
  { property: "og:title", content: "Beamtro Help" }, { property: "og:description", content: "Get help with rooms, devices, screen sharing, chat, and connections." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: HelpPage });
const guides = [{ icon: Radio, title: "Creating a room", copy: "Enter a temporary display name, select Create a room, then share the short code or invite link." }, { icon: Link2, title: "Joining a room", copy: "Paste a room code or full Beamtro link, add your display name, and join directly." }, { icon: Camera, title: "Camera and microphone", copy: "Allow browser access when asked. If unavailable, check the site permissions beside your address bar." }, { icon: MonitorUp, title: "Screen sharing", copy: "Choose Screen share, then select a tab, window, or full display. Stop sharing from the same control." }, { icon: MessageSquare, title: "Chat", copy: "Chat remains available while you talk, use video, or share your screen." }, { icon: CircleHelp, title: "Privacy", copy: "Beamtro needs no account. Room access is controlled by its temporary invite code and link." }];
function HelpPage() { return <div className="min-h-screen bg-background"><SiteHeader /><main className="mx-auto max-w-6xl px-5 py-16 sm:py-24"><span className="eyebrow">Beamtro help</span><h1 className="mt-5 font-display text-5xl font-bold leading-none sm:text-6xl">Get connected quickly.</h1><p className="mt-5 max-w-xl text-lg text-muted-foreground">The essentials for opening a line and keeping it clear.</p><div className="mt-12 grid gap-x-12 gap-y-10 md:grid-cols-2">{guides.map(({ icon: Icon, title, copy }) => <article key={title} className="help-item"><Icon /><div><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{copy}</p></div></article>)}</div><section className="mt-16 border-t border-border pt-10"><h2 className="font-display text-2xl font-semibold">Troubleshooting</h2><div className="mt-5 grid gap-3 text-sm text-muted-foreground sm:grid-cols-2"><p><strong className="text-foreground">Camera or microphone unavailable:</strong> allow access in browser site settings, then rejoin.</p><p><strong className="text-foreground">Screen sharing unavailable:</strong> use a supported desktop browser and check system recording permissions.</p><p><strong className="text-foreground">Unable to join:</strong> check the code or paste the complete invite link again.</p><p><strong className="text-foreground">Connection problems:</strong> switch networks if possible and keep the room tab open while reconnecting.</p></div></section></main><SiteFooter /></div>; }
